---
- name: start nut-server
  service: name=nut-server state=started

- name: restart nut-server
  service: name=nut-server state=restarted


- name: start nut-client
  service: name=nut-client state=started

- name: restart nut-client
  service: name=nut-client state=restarted


- name: start apache
  service: name=apache2 state=started

- name: restart apache
  service: name=apache2 state=restarted

